

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/graduate_user?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    druid:
      initial-size: 10
      max-active: 20
      max-wait: 60000
      min-idle: 8
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20


      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: graduate-user



mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.dark.graduate.user.pojo
  global-config:
    db-config:
      id-type: auto
      column-like: true
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# pageHelper
#pagehelper:
#  helperDialect: mysql

logging:
  level:
    com.dark.graduations.mapper: debug
server:
  port: 8081
